Get http://localhost:3000

###
POST http://localhost:3000/user/
Content-Type: application/json

{
    "first_name": "Tommy",
    "last_name": "Hilfiger",
    "email": "tommyhilfiger@yahoo.com",
    "password": "tommytommy"
}