Get http://localhost:3000

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "first_name": "Ben",
    "last_name": "Pepito",
    "email": "benjamin@yahoo.com",
    "password": "pingpong"
}